INSERT INTO Musicas (Nome, Duracao, Genero, Autor, Album, capa) VALUES 
('Up From the Bottom', 3, 'Rock', 'Linkin Park', 'From Zero', 'https://upload.wikimedia.org/wikipedia/pt/9/97/Linkin_Park_-_From_Zero.jpg'),
('Billie Jean', 4, 'Pop', 'Michael Jackson', 'Thriller', 'https://upload.wikimedia.org/wikipedia/pt/thumb/3/30/Michael_Jackson_-_Thriller.jpg/250px-Michael_Jackson_-_Thriller.jpg'),
('Bohemian Rhapsody', 6, 'Rock', 'Queen', 'A Night at the Opera', 'https://upload.wikimedia.org/wikipedia/pt/b/bf/A_Night_at_the_Opera_Queen.jpg'),
('Sweet Child O Mine', 5, 'Rock', 'Guns N Roses', 'Appetite for Destruction', 'https://upload.wikimedia.org/wikipedia/pt/0/06/Appetite_for_Destruction.jpg?20250711003526'),
('Lose Yourself', 5, 'Hip-Hop', 'Eminem', '8 Mile', 'https://upload.wikimedia.org/wikipedia/pt/c/c4/Eminem_TS.jpg'),
('Shape of You', 4, 'Pop', 'Ed Sheeran', '÷', 'https://upload.wikimedia.org/wikipedia/pt/d/d3/Ed_Sheeran_-_Divide.png'),
('Blinding Lights', 3, 'Synthpop', 'The Weeknd', 'After Hours', 'https://upload.wikimedia.org/wikipedia/pt/c/c1/The_Weeknd_-_After_Hours.png'),
('Hotel California', 6, 'Classic Rock', 'Eagles', 'Hotel California', 'https://i.scdn.co/image/ab67616d0000b2734637341b9f507521afa9a778'),
('Rolling in the Deep', 4, 'Soul', 'Adele', '21', 'https://upload.wikimedia.org/wikipedia/pt/thumb/c/cf/Capa_de_21_por_Adele.jpg/250px-Capa_de_21_por_Adele.jpg'),
('Despacito', 4, 'Reggaeton', 'Luis Fonsi ft. Daddy Yankee', 'Vida', 'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/e2/ef/f0/e2eff0bc-c51d-7de5-9280-6891ddcee71b/18UMGIM85289.rgb.jpg/600x600bf-60.jpg'),
('Numb', 4, 'Rock', 'Linkin Park', 'Meteora', 'https://upload.wikimedia.org/wikipedia/pt/8/83/Linkin_park-meteora_a.jpg'),
('Beat It', 4, 'Pop', 'Michael Jackson', 'Thriller', 'https://upload.wikimedia.org/wikipedia/pt/thumb/3/30/Michael_Jackson_-_Thriller.jpg/250px-Michael_Jackson_-_Thriller.jpg'),
('Don’t Stop Me Now', 3, 'Rock', 'Queen', 'Jazz', 'https://upload.wikimedia.org/wikipedia/pt/d/d9/Queen-Jazz.jpg'),
('Paradise City', 5, 'Rock', 'Guns N Roses', 'G N\ R Lies', 'https://upload.wikimedia.org/wikipedia/pt/9/9e/GnrLies.jpg'),
('The Real Slim Shady', 4, 'Hip-Hop', 'Eminem', 'The Marshall Mathers LP', 'https://upload.wikimedia.org/wikipedia/pt/a/ae/The_Marshall_Mathers_LP.jpg'),
('Perfect', 3, 'Pop', 'Ed Sheeran', '÷', 'https://upload.wikimedia.org/wikipedia/pt/d/d3/Ed_Sheeran_-_Divide.png'),
('Starboy', 3, 'Synthpop', 'The Weeknd', 'Starboy', 'https://upload.wikimedia.org/wikipedia/pt/3/39/The_Weeknd_-_Starboy.png'),
('Life in the Fast Lane', 5, 'Classic Rock', 'Eagles', 'One of These Nights', 'https://upload.wikimedia.org/wikipedia/pt/b/bf/One_of_These_Nights.jpg');
